(function(){
'use strict';
const OVERRIDE_KEY='pellerJourneyV3AdminOverrides';
const PROGRESS_KEY='pellerJourneyV3';
const base=window.CELEBRATION_BASE_CONFIG||window.CELEBRATION_CONFIG;
let working=JSON.parse(JSON.stringify(window.CELEBRATION_CONFIG));
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const clone=v=>JSON.parse(JSON.stringify(v));
function progress(){try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');}catch{return {};}}
function save(){localStorage.setItem(OVERRIDE_KEY,JSON.stringify(Object.assign({schemaVersion:3},working)));summary();preview();alert('Saved in this browser.');}
function summary(){const p=progress();const configured=[1,2,3].filter(d=>working.days[d].sponsorUrl&&!working.days[d].sponsorUrl.includes('PASTE_')).length;$('#summaryGrid').innerHTML=`<div class="summary-card"><span>Daily plans</span><strong>3</strong></div><div class="summary-card"><span>Configured URLs</span><strong>${configured}/3</strong></div><div class="summary-card"><span>Current local day</span><strong>${p.day||1}</strong></div><div class="summary-card"><span>Claimed days</span><strong>${Object.values(p.dayClaimed||{}).filter(Boolean).length}</strong></div>`;}
function renderDay(){const day=Number($('#dayFilter').value);const data=working.days[day];const card=$('#dayTemplate').content.firstElementChild.cloneNode(true);card.querySelector('#dayHeading').textContent=`Day ${day} settings`;card.querySelectorAll('[data-field]').forEach(input=>{const key=input.dataset.field;input.value=data[key]??'';input.oninput=()=>{data[key]=input.type==='number'?Number(input.value||0):input.value;preview();};});$('#dayEditor').replaceChildren(card);}
function renderRequests(){const p=progress();const statuses=['Not eligible','Submitted','Under Review','Approved','Processing','Delivered','Correction Required'];const row=(label,key)=>`<div class="editor-card"><div class="editor-head"><strong>${label}</strong><select data-status="${key}">${statuses.map(s=>`<option ${p[key]===s?'selected':''}>${s}</option>`).join('')}</select></div></div>`;$('#requestEditor').innerHTML=row('Cash withdrawal','withdrawalStatus')+row('Airtime redemption','airtimeStatus')+row('Data redemption','dataStatus');$$('[data-status]').forEach(select=>select.onchange=()=>{const current=progress();current[select.dataset.status]=select.value;localStorage.setItem(PROGRESS_KEY,JSON.stringify(current));renderRequests();summary();});}
function renderAnalytics(){const history=Array.isArray(progress().history)?progress().history.slice().reverse():[];$('#analyticsView').innerHTML=history.length?`<table class="analytics-table"><thead><tr><th>Time</th><th>Event</th><th>Details</th></tr></thead><tbody>${history.map(h=>`<tr><td>${new Date(h.at).toLocaleString()}</td><td>${escapeHtml(h.type)}</td><td><code>${escapeHtml(JSON.stringify(h.details||{}))}</code></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No local journey events yet.</div>';}
function preview(){$('#configPreview').value=JSON.stringify(Object.assign({schemaVersion:3},working),null,2);}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
$$('[data-tab]').forEach(btn=>btn.onclick=()=>{$$('[data-tab]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.tab-panel').forEach(p=>p.classList.add('hidden'));$('#'+btn.dataset.tab+'Tab').classList.remove('hidden');if(btn.dataset.tab==='requests')renderRequests();if(btn.dataset.tab==='analytics')renderAnalytics();if(btn.dataset.tab==='data')preview();});
$('#dayFilter').onchange=renderDay;$('#saveDay').onclick=save;$('#exportConfig').onclick=()=>{const blob=new Blob([JSON.stringify(Object.assign({schemaVersion:3},working),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='peller-journey-config.json';a.click();URL.revokeObjectURL(a.href);};$('#importConfig').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(parsed.schemaVersion!==3||!parsed.days)throw new Error();working=parsed;save();renderDay();}catch{alert('Invalid journey configuration.');}e.target.value='';};$('#resetOverrides').onclick=()=>{if(!confirm('Reset browser-local campaign overrides?'))return;localStorage.removeItem(OVERRIDE_KEY);working=clone(base);renderDay();summary();preview();};$('#clearProgress').onclick=()=>{if(!confirm('Clear browser-local journey progress?'))return;localStorage.removeItem(PROGRESS_KEY);sessionStorage.clear();summary();renderRequests();renderAnalytics();};renderDay();summary();preview();
})();