(function(){
'use strict';
const OVERRIDE_KEY='pellerJourneyV4AdminOverrides';
const PROGRESS_KEY='pellerJourneyV4';
const base=window.CELEBRATION_BASE_CONFIG||window.CELEBRATION_CONFIG;
let working=JSON.parse(JSON.stringify(window.CELEBRATION_CONFIG));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=v=>JSON.parse(JSON.stringify(v));
function progress(){try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');}catch{return {};}}
function parseEditor(id,label){try{const value=JSON.parse($(id).value);if(!Array.isArray(value))throw new Error();return value;}catch{alert(`${label} must be a valid JSON array.`);return null;}}
function save(){localStorage.setItem(OVERRIDE_KEY,JSON.stringify(Object.assign({schemaVersion:4},working)));summary();preview();alert('Saved in this browser.');}
function summary(){const p=progress();const mainUrls=[1,2,3].filter(d=>working.days[d].sponsorUrl&&!working.days[d].sponsorUrl.includes('PASTE_')).length;const ads=Object.values(working.ads||{}).flat();const configuredAds=ads.filter(a=>a.url&&!a.url.includes('PASTE_')).length;const challenges=Object.values(working.challenges||{}).flat().length;$('#summaryGrid').innerHTML=`<div class="summary-card"><span>Main sponsored URLs</span><strong>${mainUrls}/3</strong></div><div class="summary-card"><span>Configured ads</span><strong>${configuredAds}/${ads.length}</strong></div><div class="summary-card"><span>Fan challenges</span><strong>${challenges}</strong></div><div class="summary-card"><span>Current local day</span><strong>${p.day||1}</strong></div><div class="summary-card"><span>Claimed days</span><strong>${Object.values(p.dayClaimed||{}).filter(Boolean).length}</strong></div>`;}
function renderDay(){const day=Number($('#dayFilter').value),data=working.days[day],card=$('#dayTemplate').content.firstElementChild.cloneNode(true);card.querySelector('#dayHeading').textContent=`Day ${day} settings`;card.querySelectorAll('[data-field]').forEach(input=>{const key=input.dataset.field;input.value=data[key]??'';input.oninput=()=>{data[key]=input.type==='number'?Number(input.value||0):input.value;preview();};});$('#dayEditor').replaceChildren(card);}
function renderChat(){const day=Number($('#chatDayFilter').value);$('#chatEditor').value=JSON.stringify(working.chat[day]||[],null,2);}
function renderChallenges(){const day=Number($('#challengeDayFilter').value);$('#challengeEditor').value=JSON.stringify(working.challenges[day]||[],null,2);}
function renderAds(){const day=Number($('#adDayFilter').value);$('#adEditor').value=JSON.stringify(working.ads['day'+day]||[],null,2);}
function renderRequests(){const p=progress(),statuses=['Not eligible','Submitted','Under Review','Approved','Processing','Delivered','Correction Required'];const row=(label,key)=>`<div class="editor-card"><div class="editor-head"><strong>${label}</strong><select data-status="${key}">${statuses.map(s=>`<option ${p[key]===s?'selected':''}>${s}</option>`).join('')}</select></div></div>`;$('#requestEditor').innerHTML=row('Cash withdrawal','withdrawalStatus')+row('Airtime redemption','airtimeStatus')+row('Data redemption','dataStatus');$$('[data-status]').forEach(select=>select.onchange=()=>{const current=progress();current[select.dataset.status]=select.value;localStorage.setItem(PROGRESS_KEY,JSON.stringify(current));renderRequests();summary();});}
function renderAnalytics(){const history=Array.isArray(progress().history)?progress().history.slice().reverse():[];$('#analyticsView').innerHTML=history.length?`<table class="analytics-table"><thead><tr><th>Time</th><th>Event</th><th>Details</th></tr></thead><tbody>${history.map(h=>`<tr><td>${new Date(h.at).toLocaleString()}</td><td>${escapeHtml(h.type)}</td><td><code>${escapeHtml(JSON.stringify(h.details||{}))}</code></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No local journey events yet.</div>';}
function preview(){$('#configPreview').value=JSON.stringify(Object.assign({schemaVersion:4},working),null,2);}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
$$('[data-tab]').forEach(btn=>btn.onclick=()=>{$$('[data-tab]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.tab-panel').forEach(p=>p.classList.add('hidden'));$('#'+btn.dataset.tab+'Tab').classList.remove('hidden');if(btn.dataset.tab==='chat')renderChat();if(btn.dataset.tab==='challenges')renderChallenges();if(btn.dataset.tab==='ads')renderAds();if(btn.dataset.tab==='requests')renderRequests();if(btn.dataset.tab==='analytics')renderAnalytics();if(btn.dataset.tab==='data')preview();});
$('#dayFilter').onchange=renderDay;$('#chatDayFilter').onchange=renderChat;$('#challengeDayFilter').onchange=renderChallenges;$('#adDayFilter').onchange=renderAds;
$('#saveDay').onclick=save;
$('#saveChat').onclick=()=>{const day=Number($('#chatDayFilter').value),value=parseEditor('#chatEditor','Chat configuration');if(!value)return;working.chat[day]=value;save();};
$('#saveChallenges').onclick=()=>{const day=Number($('#challengeDayFilter').value),value=parseEditor('#challengeEditor','Challenge configuration');if(!value)return;working.challenges[day]=value;save();};
$('#saveAds').onclick=()=>{const day=Number($('#adDayFilter').value),value=parseEditor('#adEditor','Advertisement configuration');if(!value)return;working.ads['day'+day]=value;save();};
$('#exportConfig').onclick=()=>{const blob=new Blob([JSON.stringify(Object.assign({schemaVersion:4},working),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='peller-journey-v4-config.json';a.click();URL.revokeObjectURL(a.href);};
$('#importConfig').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(Number(parsed.schemaVersion)!==4||!parsed.days||!parsed.chat||!parsed.challenges||!parsed.ads)throw new Error();working=parsed;save();renderDay();renderChat();renderChallenges();renderAds();}catch{alert('Invalid V4 journey configuration.');}e.target.value='';};
$('#resetOverrides').onclick=()=>{if(!confirm('Reset browser-local campaign overrides?'))return;localStorage.removeItem(OVERRIDE_KEY);working=clone(base);renderDay();renderChat();renderChallenges();renderAds();summary();preview();};
$('#clearProgress').onclick=()=>{if(!confirm('Clear browser-local journey progress?'))return;localStorage.removeItem(PROGRESS_KEY);sessionStorage.clear();summary();renderRequests();renderAnalytics();};
renderDay();renderChat();renderChallenges();renderAds();summary();preview();
})();