(function(){
'use strict';
const OVERRIDE_KEY='pellerCelebrationAdminOverrides';
const PROGRESS_KEY='pellerCelebrationV2';
const base=window.CELEBRATION_BASE_CONFIG||window.CELEBRATION_CONFIG;
let working=JSON.parse(JSON.stringify(window.CELEBRATION_CONFIG));
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const clone=v=>JSON.parse(JSON.stringify(v));
function saveOverrides(){localStorage.setItem(OVERRIDE_KEY,JSON.stringify(working));refreshSummary();refreshPreview();alert('Saved in this browser.');}
function refreshSummary(){const tasks=Object.values(working.tasks||{}).flat();const progress=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');$('#summaryGrid').innerHTML=`<div class="summary-card"><span>Total tasks</span><strong>${tasks.length}</strong></div><div class="summary-card"><span>Active tasks</span><strong>${tasks.filter(t=>t.active).length}</strong></div><div class="summary-card"><span>Configured URLs</span><strong>${tasks.filter(t=>t.url&&!t.url.includes('PASTE_')).length}</strong></div><div class="summary-card"><span>Local completions</span><strong>${Object.keys(progress.completed||{}).length}</strong></div>`;}
function bindFields(card,item){card.querySelectorAll('[data-field]').forEach(input=>{const key=input.dataset.field;if(input.type==='checkbox')input.checked=Boolean(item[key]);else input.value=item[key]??'';input.addEventListener('input',()=>{item[key]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value||0):input.value;const heading=card.querySelector('.task-heading,.ad-heading');if(heading)heading.textContent=item.title||item.name||item.id||'Untitled';refreshPreview();});});}
function renderTasks(){const day=$('#dayFilter').value;working.tasks[day]=working.tasks[day]||[];const list=$('#taskEditor');list.innerHTML='';working.tasks[day].forEach((task,index)=>{const card=$('#taskTemplate').content.firstElementChild.cloneNode(true);bindFields(card,task);card.querySelector('.task-heading').textContent=task.title||task.id;card.querySelector('[data-remove]').onclick=()=>{working.tasks[day].splice(index,1);renderTasks();};card.querySelector('[data-move="up"]').onclick=()=>move(working.tasks[day],index,index-1,renderTasks);card.querySelector('[data-move="down"]').onclick=()=>move(working.tasks[day],index,index+1,renderTasks);list.appendChild(card);});if(!working.tasks[day].length)list.innerHTML='<div class="empty">No tasks for this day.</div>';}
function renderAds(){const place=$('#placementFilter').value;working.ads=working.ads||{};working.ads[place]=working.ads[place]||[];const list=$('#adEditor');list.innerHTML='';working.ads[place].forEach((ad,index)=>{const card=$('#adTemplate').content.firstElementChild.cloneNode(true);bindFields(card,ad);card.querySelector('.ad-heading').textContent=ad.name||ad.id;card.querySelector('[data-remove]').onclick=()=>{working.ads[place].splice(index,1);renderAds();};list.appendChild(card);});if(!working.ads[place].length)list.innerHTML='<div class="empty">No ads in this placement.</div>';}
function move(arr,from,to,render){if(to<0||to>=arr.length)return;[arr[from],arr[to]]=[arr[to],arr[from]];render();}
function renderAnalytics(){const progress=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');const history=Array.isArray(progress.history)?progress.history.slice().reverse():[];$('#analyticsView').innerHTML=history.length?`<table class="analytics-table"><thead><tr><th>Time</th><th>Event</th><th>Details</th></tr></thead><tbody>${history.map(h=>`<tr><td>${new Date(h.at).toLocaleString()}</td><td>${h.type}</td><td><code>${escapeHtml(JSON.stringify(h.details||{}))}</code></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No local events have been recorded yet.</div>';}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function refreshPreview(){$('#configPreview').value=JSON.stringify(working,null,2);}
$$('[data-tab]').forEach(btn=>btn.onclick=()=>{$$('[data-tab]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.tab-panel').forEach(p=>p.classList.add('hidden'));$('#'+btn.dataset.tab+'Tab').classList.remove('hidden');if(btn.dataset.tab==='analytics')renderAnalytics();if(btn.dataset.tab==='data')refreshPreview();});
$('#dayFilter').onchange=renderTasks;$('#placementFilter').onchange=renderAds;
$('#addTask').onclick=()=>{const day=$('#dayFilter').value;working.tasks[day].push({id:'new_task_'+Date.now(),title:'New Celebration Task',description:'Describe the activity.',category:'couple',estimatedMinutes:4,reward:0,url:'',verificationType:'manual_review',requiredAnswers:0,requiredReferrals:0,required:false,active:false});renderTasks();};
$('#addAd').onclick=()=>{const place=$('#placementFilter').value;working.ads[place].push({id:'new_ad_'+Date.now(),name:'New sponsored placement',label:'Sponsored',url:'PASTE_AD_URL_HERE',placement:place,active:false,minimumDay:1,maximumShowsPerSession:1,cooldownMinutes:30});renderAds();};
$('#saveTasks').onclick=saveOverrides;$('#saveAds').onclick=saveOverrides;
$('#exportConfig').onclick=()=>{const blob=new Blob([JSON.stringify(working,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='peller-celebration-config.json';a.click();URL.revokeObjectURL(a.href);};
$('#importConfig').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(!parsed.tasks||!parsed.campaign)throw new Error('Invalid config');working=parsed;saveOverrides();renderTasks();renderAds();}catch{alert('The selected file is not a valid campaign configuration.');}e.target.value='';};
$('#resetOverrides').onclick=()=>{if(!confirm('Reset all browser-local admin changes?'))return;localStorage.removeItem(OVERRIDE_KEY);working=clone(base);renderTasks();renderAds();refreshSummary();refreshPreview();};
$('#clearProgress').onclick=()=>{if(!confirm('Clear all browser-local campaign progress?'))return;localStorage.removeItem(PROGRESS_KEY);sessionStorage.clear();refreshSummary();renderAnalytics();};
renderTasks();renderAds();refreshSummary();refreshPreview();
})();
