(function(){
'use strict';
const CONFIG=window.CELEBRATION_CONFIG;
const STORAGE_KEY='pellerCelebrationV2';
const SESSION_KEY='pellerCelebrationSession';
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const money=(n)=>'₦'+Number(n||0).toLocaleString('en-NG');
const placeholder=(url)=>!url||url.includes('PASTE_');
const defaultState={onboarded:false,phone:'',network:'',day:1,earned:0,dailyEarned:{1:0,2:0,3:0},completed:{},pending:{},answers:{},referrals:0,assigned:{},streak:1,eligibilitySubmitted:false,referralCode:'',referredBy:'',history:[]};
function loadState(){try{return Object.assign({},defaultState,JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'));}catch{return {...defaultState};}}
let state=loadState();
state.dailyEarned=Object.assign({1:0,2:0,3:0},state.dailyEarned||{});state.completed=state.completed||{};state.pending=state.pending||{};state.answers=state.answers||{};state.assigned=state.assigned||{};state.history=Array.isArray(state.history)?state.history:[];
const incomingRef=new URLSearchParams(location.search).get('ref');if(incomingRef&&!state.referredBy)state.referredBy=incomingRef.slice(0,40);
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
function log(type,details={}){state.history.push({type,details,at:new Date().toISOString()});state.history=state.history.slice(-100);save();}
let live=4548;setInterval(()=>{live+=Math.floor(Math.random()*18)+1;const el=$('#countdowntimer');if(el)el.textContent=live;},1000);
function shuffle(arr){const copy=arr.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function taskDay(task){for(let d=1;d<=3;d++)if((CONFIG.tasks['day'+d]||[]).some(t=>t.id===task.id))return d;return state.day;}
function dayTasks(day){const key='day'+day;const tasks=(CONFIG.tasks[key]||[]).filter(t=>t.active);if(!state.assigned[key]){const required=shuffle(tasks.filter(t=>t.required));const optional=shuffle(tasks.filter(t=>!t.required));state.assigned[key]=required.concat(optional).map(t=>t.id);save();}return state.assigned[key].map(id=>tasks.find(t=>t.id===id)).filter(Boolean);}
function findTask(id){for(let d=1;d<=3;d++){const task=(CONFIG.tasks['day'+d]||[]).find(t=>t.id===id);if(task)return task;}return null;}
function currentLevel(){const count=Object.keys(state.completed).length;return [...CONFIG.campaign.supporterLevels].reverse().find(level=>count>=level.min).name;}
function statusFor(task){if(state.completed[task.id])return 'Completed';if(state.pending[task.id])return 'Awaiting verification';if(placeholder(task.url)&&['return_and_quiz','approved_callback'].includes(task.verificationType))return 'Needs owner URL';return 'Available';}
function allRequiredCompleted(){return [1,2,3].every(day=>dayTasks(day).filter(task=>task.required).every(task=>state.completed[task.id]));}
function render(){
  if(state.onboarded){$('#onboarding').classList.add('hidden');$('#dashboard').classList.remove('hidden');}else{$('#onboarding').classList.remove('hidden');$('#dashboard').classList.add('hidden');return;}
  $('#welcomeName').textContent='Welcome, '+(state.phone?'Supporter '+state.phone.slice(-4):'Supporter');$('#currentDay').textContent=state.day;$('#taskDayLabel').textContent=state.day;
  $('#cashProgress').textContent=money(state.earned)+' / '+money(CONFIG.campaign.cashTarget);$('#cashBar').style.width=Math.min(100,(state.earned/CONFIG.campaign.cashTarget)*100)+'%';$('#dailyProgress').textContent=money(state.dailyEarned[state.day])+' / '+money(CONFIG.campaign.dailyCaps[state.day]);$('#supporterLevel').textContent=currentLevel();$('#referralProgress').textContent=state.referrals+' verified';$('#streakValue').textContent='Day '+state.streak;
  const tasks=dayTasks(state.day);const next=tasks.find(task=>task.required&&!state.completed[task.id]&&!state.pending[task.id])||tasks.find(task=>!state.completed[task.id]&&!state.pending[task.id]);$('#nextTaskText').textContent=next?'Next required task: '+next.title:'All assigned activities completed for today.';renderTasks(tasks);
  const reached=state.dailyEarned[state.day]>=CONFIG.campaign.dailyCaps[state.day];$('#nextSession').classList.toggle('hidden',!reached);
  const eligible=state.day===3&&allRequiredCompleted()&&state.earned>=CONFIG.campaign.cashTarget;$('#eligibility').classList.toggle('hidden',!eligible);
}
function renderTasks(tasks){$('#taskList').innerHTML=tasks.map(task=>{const status=statusFor(task);const disabled=['Completed','Awaiting verification','Needs owner URL'].includes(status);const statusClass=status==='Completed'?'completed':status==='Awaiting verification'?'pending':'';return `<article class="task-card"><div class="task-top"><div><span class="task-category">${task.label||task.category}</span><h3>${task.title}</h3></div><span class="task-status ${statusClass}">${status}</span></div><p class="task-description">${task.description}</p><div class="task-meta"><span>⏱ ${task.estimatedMinutes} min</span><span>Reward progress: ${money(task.reward)}</span><span>${task.verificationType.replaceAll('_',' ')}</span></div>${status==='Needs owner URL'?'<p class="config-warning">Owner configuration required: replace the URL placeholder in js/config.js.</p>':''}<button class="task-action" data-task="${task.id}" ${disabled?'disabled':''}>${status==='Completed'?'COMPLETED':status==='Awaiting verification'?'AWAITING REVIEW':status==='Needs owner URL'?'URL NOT CONFIGURED':'START TASK'}</button></article>`;}).join('');$$('[data-task]').forEach(button=>button.addEventListener('click',()=>openTask(button.dataset.task)));}
function openTask(id){const task=findTask(id);if(!task)return;let body=`<span class="eyebrow">${task.category.toUpperCase()}</span><h2>${task.title}</h2><p>${task.description}</p><div class="task-meta"><span>${task.estimatedMinutes} minutes</span><span>${money(task.reward)} progress</span></div>`;if(task.url&&!placeholder(task.url))body+=`<button class="secondary-btn" id="externalTaskOpen">OPEN APPROVED CONTENT</button><p class="muted">Return to this tab and complete the local requirement. Opening the page alone does not complete the task.</p>`;if(task.verificationType==='prediction')body+=predictionForm(task);else if(task.verificationType.includes('quiz'))body+=quizForm(task);else if(task.verificationType==='message_submitted')body+=`<label>Your congratulatory message</label><textarea id="taskMessage" rows="5" minlength="${task.minimumLength||40}" placeholder="Write a respectful message..."></textarea>`;else if(task.verificationType==='supporter_card_created')body+=`<label>Name on supporter card</label><input id="cardName" placeholder="Your name"/><label>Your final prediction</label><input id="cardPrediction" placeholder="Your wedding prediction"/>`;else if(task.verificationType==='verified_referral')body+=`<div class="question-block"><strong>Verified supporters: ${state.referrals} of ${task.requiredReferrals}</strong><p>Static preview cannot verify real referrals. Use the browser-local preview control only for testing.</p></div>`;else if(task.verificationType==='manual_review')body+=`<div class="question-block"><p>Review completed activities and submit this task for administrator review.</p></div>`;body+=`<button id="completeTask" class="primary-btn">${task.verificationType==='verified_referral'?'SUBMIT FOR VERIFICATION':'COMPLETE TASK'}</button>`;$('#taskModalBody').innerHTML=body;$('#taskModal').classList.remove('hidden');if($('#externalTaskOpen'))$('#externalTaskOpen').onclick=()=>{window.open(task.url,'_blank','noopener');sessionStorage.setItem('returned:'+task.id,'opened');log('external_task_open',{taskId:task.id});};$('#completeTask').onclick=()=>completeTask(task);}
function predictionForm(task){return `<div class="question-block"><strong>${task.question}</strong>${task.options.map(option=>`<label><input type="radio" name="prediction" value="${option}"> ${option}</label>`).join('')}</div>`;}
function quizForm(task){const count=task.requiredAnswers||3;return Array.from({length:count},(_,i)=>`<div class="question-block"><strong>Question ${i+1}</strong><p>${quizQuestion(task.category,i)}</p><label><input type="radio" name="q${i}" value="a"> Option A</label><label><input type="radio" name="q${i}" value="b"> Option B</label></div>`).join('');}
function quizQuestion(category,i){const sets={peller:['Which featured moment stood out most?','What quality best describes the featured story?','Which celebration detail was highlighted?','Which fan value was most visible?','Which moment would you share?'],jarvis:['Which style option was featured?','Which colour best matches the theme?','What detail made the look distinctive?'],couple:['Which colour is central to the campaign?','What year is the celebration?','Which activity is part of the supporter journey?','What is the data reward shown?','Which couple is being celebrated?','What is the cash target?','What is the airtime amount?','How many earning days are included?'],review:['Have you reviewed your completed tasks?']};const group=sets[category]||sets.couple;return group[i%group.length];}
function completeTask(task){if(state.completed[task.id])return;if(task.verificationType==='prediction'){const selected=document.querySelector('input[name=prediction]:checked');if(!selected)return alert('Choose one prediction.');state.answers[task.id]=selected.value;}if(task.verificationType.includes('quiz')){for(let i=0;i<(task.requiredAnswers||3);i++)if(!document.querySelector(`input[name=q${i}]:checked`))return alert('Answer every question before submitting.');if(task.url&&!placeholder(task.url)&&!sessionStorage.getItem('returned:'+task.id))return alert('Open the approved content first, then return to complete the questions.');}if(task.verificationType==='message_submitted'){const value=$('#taskMessage').value.trim();if(value.length<(task.minimumLength||40))return alert('Your message is too short.');state.answers[task.id]=value;}if(task.verificationType==='supporter_card_created'){if(!$('#cardName').value.trim()||!$('#cardPrediction').value.trim())return alert('Complete both supporter card fields.');state.answers[task.id]={name:$('#cardName').value.trim(),prediction:$('#cardPrediction').value.trim()};}if(task.verificationType==='verified_referral'&&state.referrals<(task.requiredReferrals||1)){state.pending[task.id]=true;log('task_pending',{taskId:task.id,reason:'referral_verification'});closeModal();render();return alert('Submitted for verification. No reward progress is credited until the required referrals are verified.');}if(task.verificationType==='manual_review'){state.pending[task.id]=true;log('task_pending',{taskId:task.id,reason:'manual_review'});closeModal();render();return alert('Submitted for administrator review.');}creditTask(task);}
function creditTask(task){if(state.completed[task.id])return;const day=taskDay(task);const cap=CONFIG.campaign.dailyCaps[day];const remaining=Math.max(0,cap-state.dailyEarned[day]);const credit=Math.min(task.reward,remaining);state.completed[task.id]={completedAt:new Date().toISOString(),credit};delete state.pending[task.id];state.dailyEarned[day]+=credit;state.earned=Math.min(CONFIG.campaign.cashTarget,state.earned+credit);log('task_completed',{taskId:task.id,day,credit});closeModal();render();maybeShowSponsored();}
function maybeShowSponsored(){const session=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'{}');if(session.sponsoredShown)return;const ad=(CONFIG.ads.sponsoredTask||[]).find(item=>item.active&&item.minimumDay<=state.day&&!placeholder(item.url));if(!ad)return;session.sponsoredShown=true;sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));$('#sponsoredTitle').textContent=ad.name;$('#sponsoredPanel').classList.remove('hidden');$('#openSponsored').onclick=()=>{log('ad_open',{adId:ad.id,placement:'sponsoredTask',day:state.day});window.open(ad.url,'_blank','noopener');};}
function closeModal(){$('#taskModal').classList.add('hidden');}
$$('[data-close-modal]').forEach(button=>button.onclick=closeModal);$$('[data-close-sponsored]').forEach(button=>button.onclick=()=>$('#sponsoredPanel').classList.add('hidden'));
$('#go').onclick=async()=>{if(!$('#year').value)return alert('Select your network.');state.network=$('#year').value;$('#intro').classList.add('hidden');$('#loader').classList.remove('hidden');for(let i=0;i<=100;i++){if(i%4===0)$('#num').textContent=i+'%';await new Promise(resolve=>setTimeout(resolve,12));}$('#loader').classList.add('hidden');$('#info').classList.remove('hidden');};
$('#confirm').onclick=()=>{const phone=$('#name').value.replace(/\D/g,'');if(phone.length<10){$('.error').classList.remove('hidden');return;}state.phone=phone;state.onboarded=true;if(!state.referralCode)state.referralCode='PJ-'+phone.slice(-4)+'-'+Math.floor(1000+Math.random()*9000);log('onboarded',{network:state.network});render();};
$('#name').oninput=()=>$('.error').classList.add('hidden');
$('#copyReferral').onclick=async()=>{if(!state.referralCode){state.referralCode='PJ-'+(state.phone.slice(-4)||'USER')+'-'+Math.floor(1000+Math.random()*9000);save();}const link=location.origin+location.pathname+'?ref='+encodeURIComponent(state.referralCode);try{await navigator.clipboard.writeText(link);alert('Referral link copied. Real referral credit requires backend verification.');}catch{alert('Referral link: '+link);}};
$('#submitEligibility').onclick=()=>{if(!(state.day===3&&allRequiredCompleted()&&state.earned>=CONFIG.campaign.cashTarget))return alert('Complete every required task and reach the full campaign target first.');state.eligibilitySubmitted=true;log('eligibility_submitted');alert('Eligibility submitted for administrator review. No payment or reward delivery has been marked complete.');};
const openPreview=()=>$('#adminPreview').classList.remove('hidden');$('#openAdminPreview').onclick=openPreview;$('#openAdminPreviewTop').onclick=openPreview;$('#closeAdminPreview').onclick=()=>$('#adminPreview').classList.add('hidden');
$$('[data-admin]').forEach(button=>button.onclick=()=>{const action=button.dataset.admin;if(action==='approve-referral'){state.referrals+=1;for(const id of Object.keys(state.pending)){const task=findTask(id);if(task&&task.verificationType==='verified_referral'&&state.referrals>=task.requiredReferrals)creditTask(task);}log('preview_referral_approved',{count:state.referrals});render();}if(action==='approve-pending'){for(const id of Object.keys(state.pending)){const task=findTask(id);if(task&&task.verificationType!=='verified_referral')creditTask(task);}render();}if(action==='next-day'){if(state.day>=3)return alert('Already on Day 3.');const reached=state.dailyEarned[state.day]>=CONFIG.campaign.dailyCaps[state.day];if(!reached&&!confirm('This is a preview control. Advance before reaching today’s limit?'))return;state.day+=1;state.streak=Math.max(state.streak,state.day);log('preview_day_advanced',{day:state.day});render();}if(action==='reset'){localStorage.removeItem(STORAGE_KEY);sessionStorage.clear();location.reload();}});
save();render();
})();
